// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwUsdlojvlZLuqRKDM9Bcd8w6qoEdsT9k',
    appId: '1:32215506048:web:4a19fd58f58baf39f65a65',
    messagingSenderId: '32215506048',
    projectId: 'cpd-homeassignment',
    authDomain: 'cpd-homeassignment.firebaseapp.com',
    storageBucket: 'cpd-homeassignment.firebasestorage.app',
    measurementId: 'G-8Z2SFDNTDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtLAt-YzAg9lzE9RVJElK_9Xzb5z8Te00',
    appId: '1:32215506048:android:09434b0ad5e42e21f65a65',
    messagingSenderId: '32215506048',
    projectId: 'cpd-homeassignment',
    storageBucket: 'cpd-homeassignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-g58cVDa9i0abyQaQIvCwU-ivpHvikU0',
    appId: '1:32215506048:ios:7e97b9b0eac99d9ef65a65',
    messagingSenderId: '32215506048',
    projectId: 'cpd-homeassignment',
    storageBucket: 'cpd-homeassignment.firebasestorage.app',
    iosBundleId: 'com.example.homeAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-g58cVDa9i0abyQaQIvCwU-ivpHvikU0',
    appId: '1:32215506048:ios:7e97b9b0eac99d9ef65a65',
    messagingSenderId: '32215506048',
    projectId: 'cpd-homeassignment',
    storageBucket: 'cpd-homeassignment.firebasestorage.app',
    iosBundleId: 'com.example.homeAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwUsdlojvlZLuqRKDM9Bcd8w6qoEdsT9k',
    appId: '1:32215506048:web:e11c8dc63e370f54f65a65',
    messagingSenderId: '32215506048',
    projectId: 'cpd-homeassignment',
    authDomain: 'cpd-homeassignment.firebaseapp.com',
    storageBucket: 'cpd-homeassignment.firebasestorage.app',
    measurementId: 'G-R6WGZ6G6WW',
  );
}
